version: 2.1

executors:
  node-executor:
    docker:
      - image: cimg/node:18.20
    working_directory: ~/project

jobs:
  build:
    executor: node-executor
    steps:
      - checkout
      - run: npm ci
      - run: npm run build
      - persist_to_workspace:
          root: .
          paths:
            - dist

  test-e2e:
    executor: node-executor
    steps:
      - checkout
      - run: npm ci
      - run:
          name: Install Playwright Browsers
          command: npx playwright install --with-deps
      - run:
          name: Run Playwright end-to-end tests
          command: npx playwright test
      - store_artifacts:
          path: playwright-report
          destination: playwright-report

  deploy:
    executor: node-executor
    steps:
      - attach_workspace:
          at: .
      - run:
          name: Déploiement vers Render
          command: |
            curl -X POST "https://api.render.com/deploy/srv-d0q973adbo4c73brvaj0?key=Zkym-WbE_A4"

workflows:
  deploy-on-push:
    jobs:
      - build
      - test-e2e:
          requires:
            - build
      - deploy:
          requires:
            - test-e2e
